### ISSUE TITLE
Where is the code

### ISSUE THREAD

**Issue by tvixen** [goltermc/WeMosHttpDimmer#3]
Hi there
Where is The sketch, WeMosServer.ino  ?

**Comment by goltermc** [comment]
Sorry, I got sidetracked some time ago.
Take a look now. The code is not perfect but does demonstrate how to serve up a simple page on the WeMos D1 board.
Note that "dimming" is not working as I'd like (using the on board led). But on and off work fine.

**Comment by tvixen** [comment]
Super i will have a look
